version: "3.7"
name: simulation

services:
  fog:
    build: fog/
    networks:
      - fog-network
    environment:
      - QUANTITY_FOGS=${QUANTITY_FOGS}
      - MESSAGE_PROCESSING_CPU_THRESHOLD=${MESSAGE_PROCESSING_CPU_THRESHOLD}
      - PROCESS_MESSAGE_FUNCTION_REPEAT=${PROCESS_MESSAGE_FUNCTION_REPEAT}
      - PROCESS_MESSAGE_LEADING_ZEROS=${PROCESS_MESSAGE_LEADING_ZEROS}
      - ACTIVATE_AUCTION=${ACTIVATE_AUCTION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: ${QUANTITY_FOGS}
      # resources:
      #   limits:
      #     cpus: "1"
    depends_on:
      - "mosquitto"

  cloud:
    build: cloud/
    networks:
      - fog-network
    depends_on:
      - "mosquitto"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/:/mosquitto/config/:ro
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - fog-network

  client:
    build: client/
    networks:
      - fog-network
    environment:
      - QUANTITY_CLIENTS=${QUANTITY_CLIENTS}
      - QUANTITY_FOGS=${QUANTITY_FOGS}
    depends_on:
      - "fog"
    
  data_collector:
    container_name: data
    build: data_collector/
    networks:
      - fog-network
    environment:
      - QUANTITY_FOGS=${QUANTITY_FOGS}
      - QUANTITY_CLIENTS=${QUANTITY_CLIENTS}
      - SIMULATION_TIME=${SIMULATION_TIME}
      - WARMUP_TIME=${WARMUP_TIME}
      - ACTIVATE_AUCTION=${ACTIVATE_AUCTION}
    volumes:
      - ./data_collector:/data_collector
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "fog"

networks:
  fog-network:
    driver: bridge
    name: fog-network