version: "3.7"

services:
  fog_1:
    container_name: fog_1
    build: fog/
    networks:
      - fog-network
    environment:
      - broker_ip=192.168.0.8
      - broker_port=1883
      - broker_message=fog_1

  fog_2:
    container_name: fog_2
    build: fog/
    networks:
      - fog-network
    environment:
      - broker_ip=192.168.0.8
      - broker_port=1884
      - broker_message=fog_2

  mosquitto_1:
    container_name: mosquitto_1
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/:/mosquitto/config/:ro
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - fog-network

  mosquitto_2:
    container_name: mosquitto_2
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/:/mosquitto/config/:ro
    ports:
      - 1884:1883
      - 9002:9001
    networks:
      - fog-network

  gateway:
    container_name: gateway
    build: gateway/
    environment:
      - broker_ip=192.168.0.8
      - broker_ports=1883 1884
      - fogs_uplink=100 170
      - fogs_latency=50 110
      - fogs_number=2
    networks:
      - fog-network

networks:
  fog-network:
    driver: bridge
    name: fog-network