version: "3.7"

services:
  fog:
    container_name: fog
    build: fog/
    networks:
      - fog-network
  
  mqtt-client:
    container_name: client
    build: client/
    networks:
      - fog-network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ./mosquitto/:/mosquitto/config/:ro
      #- ./mosquitto-log/:/mosquitto/log/
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - fog-network

networks:
  fog-network:
    driver: bridge
    name: fog-network